spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
      hibernate.default_schema: jwt_sch
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      expiration: 86400000
      refresh-token:
        expiration: 604800000

